mqtt:
  fqdn: broker.hivemq.com
  port: 1883
influxdb:
  fqdn: westeurope-1.azure.cloud2.influxdata.com
  TokenRead: yXyyfBMlEHjCgyXUXREejJhomgg_Su2JzaV0v0pBcaJvIAAnSB4nz2qYy2LLQSZ1gNPPhEAc8rYg8rJLAmTmJA==
  TokenWrite: yXyyfBMlEHjCgyXUXREejJhomgg_Su2JzaV0v0pBcaJvIAAnSB4nz2qYy2LLQSZ1gNPPhEAc8rYg8rJLAmTmJA==
  organisation: dan.b@ritchiedaffin.com
sites:
  - name: bldg_59
    devices: [
      electricalMeter, 
      gasMeter
      ]